model:
  arch: minigpt4

  # vit encoder
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp16"
  freeze_vit: True
  has_qformer: False

  model_type: pretrain_llama2
  max_txt_len: 160
  end_sym: "</s>"
  low_resource: False
  prompt_template: "[INST] {} [/INST] "
  ckpt: "/home/ant/llm-hal/efuf/checkpoints/minigpt4_llama2_7b/pretrained.pth"

  # generation configs
  prompt: ""

  # llama_model: "/root/.cache/huggingface/hub/models--meta-llama--Llama-2-7b-chat-hf"
  llama_model: "/home/ant/llm-hal/HA-DPO/ha_dpo/models/minigpt4/merged_minigpt4_ha_dpo"

preprocess:
  vis_processor:
    train:
      name: "blip2_image_train"
      image_size: 224
    eval:
      name: "blip2_image_eval"
      image_size: 224
  text_processor:
    train:
      name: "blip_caption"
    eval:
      name: "blip_caption"

datasets:
  cc_sbu_align:
    vis_processor:
      train:
        name: "blip2_image_eval"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"

run:
  task: image_text_pretrain
